version: '2'
services:
  webserver:
    image: phpstorm/php-73-apache-xdebug-27
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/sites-available/:/etc/apache2/sites-available
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal