index:
    path: /
    controller: App\Controller\DefaultController::index
api_cards_list:
    path: /api/cards
    controller: App\Controller\ApiController:cardsList
api_conditions_list:
    path: /api/conditions
    controller: App\Controller\ApiController:conditionsList
api_scenarios_list:
    path: /api/scenarios
    controller: App\Controller\ApiController:scenariosList
api_simulation:
    path: /api/simulation
    methods: POST
    requirements:
        _format: json
    controller: App\Controller\ApiController:simulation
