# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Factory\ScenarioFactory:
        class: App\Factory\ScenarioFactory
        autowire: true
        calls:
            - method: registerScenario
              arguments:
                  - App\Scenarios\StartingHand
            - method: registerScenario
              arguments:
                  - App\Scenarios\GeneralScenario

    App\Factory\ConditionFactory:
        class: App\Factory\ConditionFactory
        autowire: true
        calls:
            - method: registerCondition
              arguments:
                  - App\Conditions\ExactlyXLands
            - method: registerCondition
              arguments:
                  - App\Conditions\AtLeastXLands
            - method: registerCondition
              arguments:
                  - App\Conditions\AtMostXLands
            - method: registerCondition
              arguments:
                  - App\Conditions\HasCard
            - method: registerCondition
              arguments:
                  - App\Conditions\CanCast


    App\Service\DataLoader:
        class: App\Service\DataLoader
        autowire: true
        calls:
            - method: loadDataFromFile
              arguments:
                  - 'data/GRN.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/RNA.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/WAR.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/M20.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/ELD.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/THB.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/IKO.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/M21.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/ZNR.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/KHM.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/STX.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/AFR.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/MID.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/VOW.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/NEO.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/SNC.json'
            - method: loadDataFromFile
              arguments:
                  - 'data/DMU.json'
